"""
SQLModel sqltypes compatibility shim.

Provides AutoString for historical Alembic migrations.
AutoString is just a String without a length constraint.
"""

from sqlalchemy import String


class AutoString(String):
    """
    SQLModel-compatible AutoString type.

    This is a simple String type without length constraints,
    used in historical Alembic migrations generated by SQLModel.
    """

    def __init__(self):
        super().__init__()
