project_id: 854226
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true
files:
  - source: /frontend/src/messages/en-US.json
    ignore:
      - /frontend/src/messages/pseudo.json
    translation: /frontend/src/messages/%locale%.json
