"""Add category_rules table for v0.3

Revision ID: 6b27d8fc1026
Revises: 1b7c2fce9b4b
Create Date: 2025-11-27 13:33:16.602123

"""


# revision identifiers, used by Alembic.
revision = '6b27d8fc1026'
down_revision = '1b7c2fce9b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
