"""add import_sessions table and link to transactions

Revision ID: 6ce6205b5a58
Revises: b2f2d958aa11
Create Date: 2025-11-28 08:49:50.345475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6ce6205b5a58'
down_revision = 'b2f2d958aa11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('format_type', sa.String(), nullable=False),
    sa.Column('account_source', sa.String(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip alter_column for import_formats - SQLite doesn't support it and the enum values work as strings
    op.add_column('transactions', sa.Column('import_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_import_session_id'), 'transactions', ['import_session_id'], unique=False)
    # SQLite doesn't enforce foreign keys by default, skip explicit FK creation
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_import_session_id'), table_name='transactions')
    op.drop_column('transactions', 'import_session_id')
    op.drop_table('import_sessions')
    # ### end Alembic commands ###
