"""add sort_order and color to tags

Revision ID: afa00d0722eb
Revises: c3d4e5f6a7b8
Create Date: 2025-11-29 07:45:58.350189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa00d0722eb'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add sort_order with a default value for SQLite compatibility
    op.add_column('tags', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tags', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'color')
    op.drop_column('tags', 'sort_order')
    # ### end Alembic commands ###
