"""Add recurring_patterns table for v0.3

Revision ID: b2f2d958aa11
Revises: 6b27d8fc1026
Create Date: 2025-11-27 14:26:35.970611

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b2f2d958aa11'
down_revision = '6b27d8fc1026'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_min', sa.Float(), nullable=False),
    sa.Column('amount_max', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'monthly', 'quarterly', 'yearly', name='recurringfrequency'), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'ended', name='recurringstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_patterns_frequency'), 'recurring_patterns', ['frequency'], unique=False)
    op.create_index(op.f('ix_recurring_patterns_merchant'), 'recurring_patterns', ['merchant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_patterns_merchant'), table_name='recurring_patterns')
    op.drop_index(op.f('ix_recurring_patterns_frequency'), table_name='recurring_patterns')
    op.drop_table('recurring_patterns')
    # ### end Alembic commands ###
